# Generated by Django 4.0.2 on 2022-02-18 19:42

from django.db import migrations, models
import uploads.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=uploads.models.user_directory_path)),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
