# Generated by Django 4.0.2 on 2022-02-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='url',
        ),
    ]
